### ISSUE TITLE
Testing: Tracking Issue

### ISSUE THREAD

**Issue by camerondurham** [camerondurham/ch#3]
### Unit Tests

Unit tests for main command functions and helper functions (if they have enough logic).

- [x] docker container utils
- [x] docker api utils
- [ ] create command
  - [x] helper functions
  - [ ] main command
- [ ] delete command
- [ ] list command
- [ ] start command
  - [x] helper functions
  - [ ] main command 
- [ ] shell command
- [ ] update command

### Package Integration Tests

Add package integration tests to test CLI changes end-to-end. This should prevent having to manually test and build binary for testing and increase confidence on CLI changes or added features.

- [ ] add boilerplate integration test for root command
- [ ] cover 50% commands in integration tests
- [ ] (stretch) require PRs with passing tests for all commits to main branch
